import React from 'react';
import { InvestmentTier } from './types';

// New partnership options for the owners page
export const OWNERS_PARTNERSHIP_OPTIONS = [
  {
    title: 'Royalty + Platform Equity',
    type: 'Primary Option',
    typeLabel: 'Preferred',
    icon: 'star',
    points: [
      'Ongoing royalty participation tied to asset-level performance',
      'Minority equity participation in the GRIDLINE platform',
      'No forced exit at closing',
      'Preserves operating continuity',
      'Aligns near-term income with long-term platform value',
    ],
    description: 'Best suited for owners seeking continued cash flow with exposure to institutional rerating.',
    highlighted: true,
  },
  {
    title: 'Owner Financing + Platform Equity',
    type: 'Secondary Option',
    typeLabel: 'Secondary',
    icon: 'link',
    points: [
      'Agreed enterprise valuation',
      'Deferred consideration via owner financing',
      'Interest accrual over time',
      'Repayment from free cash flow and/or future liquidity events',
      'Minority platform equity participation',
    ],
    description: 'Best suited for owners seeking deferred liquidity with strong alignment.',
    highlighted: false,
  },
  {
    title: 'Partial Cash / Partial Equity',
    type: 'Alternative Option',
    typeLabel: 'Alternative',
    icon: 'scale',
    points: [
      'Partial liquidity at closing',
      'Remaining value contributed as platform equity',
      'Increased capital and execution complexity',
      'Longer timelines',
      'Reduced alignment relative to primary structures',
    ],
    description: 'Used selectively where partial liquidity is required.',
    highlighted: false,
  },
];

export const INVESTMENT_TIERS: InvestmentTier[] = [
  {
    id: 'seed',
    name: 'Seed Capital',
    minInvestment: '$1M Minimum',
    focus: 'Direct Equity Swap & Site Acquisition',
    targetYield: '30%+',
    listingHorizon: '48 Months',
    multiplierPath: '2x Entry → 12x Exit'
  },
  {
    id: 'core',
    name: 'Core Growth',
    minInvestment: '$5M Asset Valuation',
    focus: 'Consolidation & Infrastructure (Specific Criteria Apply)',
    targetYield: '15-20%',
    listingHorizon: '24-36 Months',
    multiplierPath: '5x Entry → 12x Exit'
  }
];

export const ASSET_STRENGTHS = [
  'Embedded growth capacity without new land or greenfield development',
  'Diversified end-market exposure',
  'Anchor tenancy stability (SAINS – 11-year contract)',
  'Operating leverage at current margins',
  'Clean ownership structure enabling straightforward execution'
];

export const PARTNERSHIP_OPTIONS = [
  {
    title: 'Vendor Finance with Platform Equity',
    type: 'Primary Option',
    icon: 'link',
    points: [
      'Agreed enterprise valuation',
      'Deferred consideration via vendor financing',
      'Interest accrual over time',
      'Repayment from free cash flow and/or liquidity events',
      'Minority equity participation in GRIDLINE'
    ]
  },
  {
    title: 'Partial Cash / Partial Equity',
    type: 'Alternative Option',
    icon: 'scale',
    points: [
      'Partial liquidity at close',
      'Increased execution complexity',
      'Longer timelines',
      'Reduced alignment compared to Option 1'
    ]
  },
  {
    title: 'All Equity Contribution',
    type: 'Fallback Option',
    icon: 'alert',
    points: [
      'No immediate liquidity',
      'Full exposure to early-stage platform risk',
      'Limited alignment with GRIDLINE governance objectives'
    ]
  }
];

// DC Owner Survey Questions (used on progress page survey step)
export const DC_SURVEY_QUESTIONS = [
  { key: 'ownershipStructure', label: 'Ownership Structure', question: 'Is the data centre fully owned, or are there any external shareholders or partners involved?', placeholder: 'e.g., Fully owned / 70% owned with 30% external partner' },
  { key: 'currentPowerUtilisation', label: 'Current Power Utilisation', question: 'What is the current IT load and overall power utilisation of the facility?', placeholder: 'e.g., 5MW IT load, 60% utilisation' },
  { key: 'powerScalability', label: 'Power Scalability', question: 'What is the maximum designed power capacity the facility can scale to?', placeholder: 'e.g., 20MW maximum capacity' },
  { key: 'customerBase', label: 'Customer Base', question: 'Approximately how many active customer contracts are in place?', placeholder: 'e.g., 15 active contracts' },
  { key: 'customerConcentration', label: 'Customer Concentration', question: 'What percentage of total revenue is generated by the top three customers?', placeholder: 'e.g., Top 3 customers = 65% of revenue' },
  { key: 'contractTenure', label: 'Contract Tenure', question: 'What is the typical contract length and renewal profile across customers?', placeholder: 'e.g., 3-5 year terms, 85% renewal rate' },
  { key: 'anchorTenants', label: 'Anchor Tenant(s)', question: 'Who are the anchor tenant(s), and what is the remaining contract term in place?', placeholder: 'e.g., Major telco, 8 years remaining' },
  { key: 'networkConnectivity', label: 'Network Connectivity', question: 'How many network carriers are available on-site or through existing partnerships?', placeholder: 'e.g., 6 carriers on-site' },
  { key: 'annualRevenue', label: 'Annual Revenue', question: 'What is the current annual revenue (and, if available, historical year-on-year figures)?', placeholder: 'e.g., MYR 25M (2024), MYR 22M (2023)' },
  { key: 'ebitdaRange', label: 'EBITDA Range', question: 'What is the typical EBITDA range or margin for the facility?', placeholder: 'e.g., 35-40% EBITDA margin' },
  { key: 'capitalOutlook', label: 'Capital & Maintenance Outlook', question: 'Are there any major maintenance events or capital expenditures anticipated within the next 12 to 24 months?', placeholder: 'e.g., Generator upgrade planned Q3 2025' },
];

// Pipeline steps configuration
export const PIPELINE_STEPS = [
  { number: 1, key: 'visitedWebsite', label: 'Visit Website', description: 'You found us', phase: 'pre' as const },
  { number: 2, key: 'registeredInterest', label: 'Register Interest', description: 'Contact info submitted', phase: 'pre' as const },
  { number: 3, key: 'bookMeeting', label: 'Book Meeting', description: 'Schedule a call with our team', phase: 'pre' as const },
  { number: 4, key: 'shareDCDetails', label: 'Share DC Details', description: 'Complete the facility survey', phase: 'pre' as const },
  { number: 5, key: 'haveMeeting', label: 'Have Meeting', description: 'Meet with the GRIDLINE team', phase: 'pre' as const },
  { number: 6, key: 'confirmNextSteps', label: 'Confirm Next Steps', description: 'Agree on path forward', phase: 'pre' as const },
  { number: 7, key: 'shareFinancials', label: 'Share Financials', description: 'Provide financial documentation', phase: 'post' as const },
  { number: 8, key: 'prepareReport', label: 'Prepare Report', description: 'GRIDLINE prepares valuation report', phase: 'post' as const },
  { number: 9, key: 'presentOffer', label: 'Present Offer', description: 'Review partnership proposal', phase: 'post' as const },
  { number: 10, key: 'dueDiligence', label: 'Due Diligence', description: 'Formal verification process', phase: 'post' as const },
  { number: 11, key: 'loi', label: 'LOI', description: 'Letter of Intent', phase: 'post' as const },
  { number: 12, key: 'closing', label: 'Closing', description: 'Finalise partnership agreement', phase: 'post' as const },
];

export const FEATURES = [
  {
    title: 'Asset Aggregation',
    description: 'We bundle high-quality data center assets into a unified portfolio for public markets.',
    icon: (
      <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
      </svg>
    )
  },
  {
    title: 'Listing Readiness',
    description: 'Institutional-grade governance designed to meet public exchange requirements.',
    icon: (
      <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
      </svg>
    )
  },
  {
    title: 'AI Workloads',
    description: 'Infrastructure optimized for high-density compute and liquid cooling.',
    icon: (
      <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
      </svg>
    )
  }
];
